# Generated by Django 6.0.5 on 2026-06-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_shortlist_status_and_more'),
        ('recruitment', '0007_screeningresult_resume_source'),
    ]

    operations = [
    ]
